import { getNumberRandomic } from "./getNumberRandomic";

export function getLoremRandomic(min: number, max: number): string {
  const words = [
    "Lorem",
    "ipsum",
    "dolor",
    "sit",
    "amet",
    "consectetur",
    "adipiscing",
    "elit",
    "Sed",
    "tempor",
    "enim",
    "in",
    "scelerisque",
    "mattis",
    "Maecenas",
    "eget",
    "lacus",
    "rhoncus",
    "fermentum",
    "turpis",
    "ac",
    "viverra",
    "Nullam",
    "eu",
    "tortor",
    "eros",
    "Vestibulum",
    "ante",
    "primis",
    "faucibus",
    "orci",
    "luctus",
    "et",
    "ultrices",
    "posuere",
    "cubilia",
    "Curae",
    "Suspendisse",
    "nec",
    "suscipit",
    "purus",
    "In",
    "aliquam",
    "dignissim",
    "tristique",
    "facilisis",
    "convallis",
    "Etiam",
    "a",
    "lectus",
    "tincidunt",
    "risus",
    "tellus",
    "interdum",
    "efficitur",
    "Nam",
    "justo",
    "id",
    "diam",
    "ullamcorper",
    "varius",
    "Curabitur",
    "fringilla",
    "elementum",
    "at",
    "commodo",
    "vel",
    "nulla",
    "Donec",
    "sem",
    "dictum",
    "elit",
    "bibendum",
    "essentially unchanged",
    "look like",
    "search for lorem ipsum",
    " to popular belief",
    "Hampden-Sydney College",
    "ndoubtable source",
    "The standard chunk of Lorem",
    "to generate Lorem",
    "predefined chunks as necessary",
    "over 2000 years old",
  ];

  let lorem = "";

  for (let i = 0; i < 1; i++) {
    const randomWords = Array.from({ length: 70 }, () => words[Math.floor(Math.random() * words.length)]);
    const paragraph = randomWords.join(" ");
    lorem += paragraph + "\n\n";
  }

  const numberRandomic = getNumberRandomic(min, max);

  return lorem.trim().slice(0, numberRandomic);
}
